### ISSUE TITLE
Add players

### ISSUE THREAD

**Issue by henrijs** [crobertsbmw/deckofcards#10]
Hmm, not sure if useful, but what about tracking which card is where? Possible states - in deck (no state), in hand (of player ID), in game (by player ID), discarded.

Nice API, BTW.

**Comment by harrisonhjones** [comment]
Yes. It would be nice to be able to track player/card state. 

For hearts (for example) you'd need the following card states:

- In Deck
- In Hand (by player)
- In Field/Game (by player)
- In "backhand" (probably called something else) (by player)

Other useful states:

- Discard pile

And of course, if you ever went as far as to enable things like MtG or complex card games you'd really need to abstract the above states so that they could go "anywhere" (exiled, removed from game, discarded, other crazy MtG card states, etc)

**Comment by Gooseus** [comment]
I think the idea is that a card has to be in a Deck/Hand/Pile.

Whatever you call it, it's basically the same thing - if I draw a card, now it's not in the main Deck, it's in my Deck (or Hand).  If I have 5 cards in my deck, I should be able to shuffle them and then draw one from my Deck to the Field.

Though I wonder if the Field and Hand are more constructs of the game and separate from the actual pure Deck API?

Each game has different properties for the Hand and the Field.  If we're playing Hold-em, the Hand is only 2 cards (player facing) and the Field is 5 cards face-up, which are pulled at different points of play (always burning one card in between).  If we're playing another poker variant, the Hand and Field may have variations of face-down, playing-facing and face-up cards at different points of play.  If we're playing Go Fish, the field is all face-down and you can assume the deck is shuffled between each Fishing.

I think trying to capture all that is a fools errand... however, the idea of allowing an "empty" Deck to be created (potentially linked to an Original or Master Deck) could be useful and simple enough.

Maybe call them Piles (or Hand probably works) originating from a Deck?

A card game application would make a Pile for each player and a Pile for the Field and it'd be up to them to handle the shuffling, turning and moving of the cards between decks while the platform simply makes sure you don't add the same card to multiple piles or look at a card that is considered "down-facing"?

**Comment by Gooseus** [comment]
Really distracting me today at work...  Some more thoughts for your consideration:

Deck v. Pile

A Deck of cards is a "stack" or other ordered array type.  A Pile would be more like a set or unordered array type.

A Pile would be what you discard into when playing Go Fish and the order that the cards are added to the Pile would be irrelevant and any drawing from the Pile would be random (essentially a shuffle each time you draw from a Pile might be good enough).

In Gin the discard pile is actually a Deck because is is ordered by discard time and is LIFO (making it an actual stack).

Again, I still think that this issue should really be about supporting the type of Deck actions that will allow any third party game to implement the type of play(ers) they will need.

**Comment by crobertsbmw** [comment]
Here is what I am thinking:
GIve every card a unique ID and allow the user to make api calls to move cards between 'piles'. A pile would basically be a stack, but you could make a call that would shuffle the pile as well. Stacks could be dynamically created and assigned ID's based on whatever the user named them. Something like:

/deck/<deck_id_number>/pile1/add/?card=card_unique_id. 
This would create a pile, called pile1, if it didn't already exist and the card to that pile.

/deck/<deck_id_number>/pile1/draw/?count=1. 
Could draw the top card from that pile

/deck/<deck_id_number>/pile1/shuffle/
Would shuffle the pile

Is this what everyone is thinking?

**Comment by swapagarwal** [comment]
:+1: This (stack API calls) would allow having different piles for each player and handle #12 as well.

**Comment by crobertsbmw** [comment]
Sorry this took me so long. It was a little harder than I anticipated.

**Comment by Gooseus** [comment]
Nice, I like the approach!
