### ISSUE TITLE
Last card not drawn when drawing multiple specific cards from Pile.

### ISSUE THREAD

**Issue by NicolasBrownGL** [crobertsbmw/deckofcards#113]
1. Created new deck: https://deckofcardsapi.com/api/deck/new?jokers_enabled=true
2. Drew top 13 cards (Spades): https://deckofcardsapi.com/api/deck/{{new_deck_j_id}}/draw/?count=13
3. Created a pile from drawn cards (AS,2S) named 'spades_pile':   https://deckofcardsapi.com/api/deck/{{new_deck_j_id}}/pile/spades_pile/add/?cards=AS,2S
4. Added rest of drawn cards to pile: https://deckofcardsapi.com/api/deck/{{new_deck_j_id}}/pile/spades_pile/add/?cards=3S,4S,5S,6S,7S,8S,9S,0S,JS,QS,KS
5. Listed cards in pile: https://deckofcardsapi.com/api/deck/{{new_deck_j_id}}/pile/spades_pile/list/
OK so far but when drawing 4 specific cards from pile:
http://deckofcardsapi.com/api/deck/{{new_deck_j_id}}/pile/spades_pile/draw/?cards=5S,6S,7S,8S

Expected result is that all 4 drawn cards are listed and remaining number of cards in pile is 9
Actual result is that last value passed(8S) is not listed and remaining number of cards in pile is 10

**Comment by fecresgam** [comment]
Hi,

I've also try to replicate this issue. Everything is working properly, @crobertsbmw .

If you want to execute it just clone my repo
https://github.com/fecresgam/karate-deckofcards

and execute 
`mvn clean test -Dkarate.options="--tags @issue113"`.

I suggest to close this issue since nobody seems to be able to replicate it, @crobertsbmw .

**Comment by crobertsbmw** [comment]
Thanks!
