### ISSUE TITLE
Consider adding functionality for deck info

### ISSUE THREAD

**Issue by navigaid** [crobertsbmw/deckofcards#32]
Suppose you're given the deck_id only, how do you know the number of cards in the deck and weather it is shuffled or not?
For example, I wish to get the following information after I visit the link
http://deckofcardsapi.com/api/deck/******

{"deck_id": "******", "success": true, "remaining": 52, "shuffled": true}

**Comment by crobertsbmw** [comment]
I have added that functionality just as you have outlined. 
Because previously I wasn't keeping track of the shuffled state of each deck, I haven't added this feature to the docs page yet (basically all the decks in the database have shuffled=False). In a week or two, when all these old deck's have phased out, and we have the shuffled state saved for all decks, then I will edit the main documentation page.

Thanks for the suggestion. Let me know if it works for you. Also, I would love to hear what you are doing with the API ( crobertsbmw at gmail ).
